Change from `Why?` to `Why DiscordJS?`
discordjs/website pull request #84
Opened 2021-07-15 20:16 UTC by Panquesito7

Things added/changed:

- Change from `Why?` to `Why DiscordJS?` on the index page.
  - IMO, I think this way looks better as it doesn't look so empty.

2021-07-18 10:00 UTC, hickatheworld commented
Such a change would make more sense if it was written `discord.js` instead of `DiscordJS`

2021-07-22 10:15 UTC, xHyroM requested changes

2021-07-22 10:15 UTC, xHyroM commented on src/pages/index.vue
> +			<h2>Why DiscordJS?</h2>
Why discord.js ?

2021-07-30 14:32 UTC, iCrawl commented
Meh.

2021-07-30 14:32 UTC, closed without merging

2021-08-31 00:27 UTC, Panquesito7 commented
Sorry for not updating in the right time. Should I change it to `discord.js`?